### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sulenn** [mokeychan/etherumForeverWords#1]
执行 `npm start` 指令出错

![image](https://user-images.githubusercontent.com/45839525/51449441-fcffc100-1d66-11e9-9063-fe324a3bf56b.png)

麻烦大佬帮看一下，谢谢

**Comment by sulenn** [comment]
解决了，打扰了。

图中的问题是缺少 `aphrodite` 和 `react-magic`这两个模块

通过 `npm install packageName` 安装即可

**Comment by WEIFZH** [comment]
@sulenn 这位同仁，请问你在编译时有没有碰到过图示问题，
![image](https://user-images.githubusercontent.com/38351273/52786272-6ee0d700-3095-11e9-80d5-817de24add69.png)不知是否有可行的解决方案？

**Comment by sulenn** [comment]
> @sulenn 这位同仁，请问你在编译时有没有碰到过图示问题，
> ![image](https://user-images.githubusercontent.com/38351273/52786272-6ee0d700-3095-11e9-80d5-817de24add69.png)不知是否有可行的解决方案？

solidity 编译器不匹配。换成0.4.2版本的应该就可以了

**Comment by afanxingzhou** [comment]
![image](https://user-images.githubusercontent.com/14249566/54084843-ecd08f00-4370-11e9-83f3-4b4225e83cc4.png)
执行npm i报错 , 是nodejs版本过高的原因吗
